server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        linger.ms: 5

app:
  kafka:
    topic: "order.events"